#!/bin/bash

#Script to execute the tcl script and the python code for every TCP Variant and CBR rate
echo "-------------Tahoe----------------"
echo "CBR      Throughput               Latency         Packet Drop Rate"
a=(1 2 3 4 5 5.5 6 6.5 7 7.5 8 8.5 9 9.3 9.6 9.8 10)

for i in ${a[@]}
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns eg.tcl Tahoe $i
printf $i
./pyth
done

echo "==========================================================================================="
echo "------------------Reno-------------------"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in ${a[@]}
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns eg.tcl Reno $i
printf $i
./pyth
done

echo "==========================================================================================="
echo "------------------Newreno-----------------------"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in ${a[@]}
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns eg.tcl Newreno $i
printf $i
./pyth
done

echo "==========================================================================================="
echo "------------------Vegas----------------------------------"
echo "CBR      Throughput               Latency         Packet Drop Rate"
for i in ${a[@]}
do
/course/cs4700f12/ns-allinone-2.35/ns-2.35/ns eg.tcl Vegas $i
printf $i
./pyth
done

